const SUPABASE_URL='https://boaqzdyfsosswqvjgsjn.supabase.co';
const SUPABASE_KEY='sb_publishable_'+'JlneB01f5LDJ4VBO_n1E7Q_jXn5JBky';
const GUEST_KEY='sixpack_guest_cart';
const getGuest=()=>{try{const v=JSON.parse(localStorage.getItem(GUEST_KEY)||'[]');return Array.isArray(v)?v:[]}catch{return[]}};
const setGuest=v=>localStorage.setItem(GUEST_KEY,JSON.stringify(v));
let db=null,supabaseLoad=null;
function getDb(){try{if(!db&&window.supabase?.createClient)db=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);return db}catch{return null}}
function loadSupabase(){if(window.supabase?.createClient)return Promise.resolve(window.supabase);if(supabaseLoad)return supabaseLoad;supabaseLoad=new Promise(resolve=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2';s.async=true;s.onload=()=>resolve(window.supabase||null);s.onerror=()=>resolve(null);document.head.appendChild(s);setTimeout(()=>resolve(window.supabase||null),3500)});return supabaseLoad}
async function currentUser(){const c=getDb()||((await loadSupabase())&&getDb());if(!c)return null;try{const {data}=await c.auth.getUser();return data?.user||null}catch{return null}}
async function liveSize(productId,size){if(!size)return 0;const c=getDb()||((await loadSupabase())&&getDb());if(!c)return 0;try{const {data}=await c.from('product_inventory').select('stock,reserved').eq('product_id',productId).eq('size',size).maybeSingle();return data?Math.max(0,Number(data.stock||0)-Number(data.reserved||0)):0}catch{return 0}}
async function serverCart(c,userId){try{const {data,error}=await c.from('cart_items').select('product_id,quantity,size,products(id,name,brand,category,price,image,stock,sizes,size_stock)').eq('user_id',userId);if(error)throw error;return (data||[]).map(x=>({...x,product:x.products}))}catch{return []}}
async function mergeGuestToUser(c,u,guest){if(!guest.length)return;for(const item of guest){try{const max=Number(item.size?await liveSize(item.product_id,item.size):item.product?.stock||0)||Number(item.product?.size_stock?.[item.size]||0);if(max<=0)continue;const existing=await c.from('cart_items').select('quantity').eq('user_id',u.id).eq('product_id',item.product_id).eq('size',item.size||'').maybeSingle();const next=Math.min(Number(existing.data?.quantity||0)+Number(item.quantity||1),max);await c.from('cart_items').upsert({user_id:u.id,product_id:item.product_id,quantity:next,size:item.size||''},{onConflict:'user_id,product_id,size'})}catch(e){console.warn('guest cart merge item failed',e)}}setGuest([])}
async function getCart(){const guest=getGuest();const c=getDb()||((await loadSupabase())&&getDb());const u=c?await currentUser():null;if(!u)return guest;if(guest.length)await mergeGuestToUser(c,u,guest);return serverCart(c,u.id)}
async function addToCart(product,size='',quantity=1){if(!product?.id)throw new Error('PRODUCT_REQUIRED');const hasSizes=Array.isArray(product.sizes)&&product.sizes.length>0;if(hasSizes&&!size)throw new Error('SIZE_REQUIRED');let max=size?await liveSize(product.id,size):Number(product.stock||0);if(size&&max<=0)max=Number(product.size_stock?.[size]||0);if(max<=0)throw new Error(size?'SIZE_OUT_OF_STOCK':'OUT_OF_STOCK');const c=getDb()||((await loadSupabase())&&getDb());const u=c?await currentUser():null;if(!u){const guest=getGuest();const i=guest.findIndex(x=>String(x.product_id)===String(product.id)&&String(x.size||'')===String(size||''));if(i>=0)guest[i].quantity=Math.min(Number(guest[i].quantity||0)+Number(quantity||1),max);else guest.push({product_id:product.id,quantity:Math.min(Number(quantity||1),max),size,product});setGuest(guest);return {guest:true}}const guest=getGuest();if(guest.length)await mergeGuestToUser(c,u,guest);const existing=await c.from('cart_items').select('quantity').eq('user_id',u.id).eq('product_id',product.id).eq('size',size).maybeSingle();const next=Math.min(Number(existing.data?.quantity||0)+Number(quantity||1),max);const {error}=await c.from('cart_items').upsert({user_id:u.id,product_id:product.id,quantity:next,size},{onConflict:'user_id,product_id,size'});if(error)throw error;return {guest:false}}
async function removeFromCart(productId,size=''){const guest=getGuest();if(guest.length){setGuest(guest.filter(x=>!(String(x.product_id)===String(productId)&&String(x.size||'')===String(size||''))));return}const c=getDb()||((await loadSupabase())&&getDb());if(!c)return;const u=await currentUser();if(!u)return;const {error}=await c.from('cart_items').delete().eq('user_id',u.id).eq('product_id',productId).eq('size',size);if(error)throw error}
async function changeQty(productId,size,quantity){if(quantity<=0)return removeFromCart(productId,size);const guest=getGuest();if(guest.length){const i=guest.findIndex(x=>String(x.product_id)===String(productId)&&String(x.size||'')===String(size||''));if(i>=0){const fallback=Number(guest[i].product?.size_stock?.[size]||guest[i].product?.stock||quantity);guest[i].quantity=Math.min(Number(quantity),fallback);setGuest(guest)}return}const max=await liveSize(productId,size);if(max<=0)return removeFromCart(productId,size);const c=getDb()||((await loadSupabase())&&getDb());if(!c)return;const u=await currentUser();if(!u)return;const {error}=await c.from('cart_items').update({quantity:Math.min(Number(quantity),max)}).eq('user_id',u.id).eq('product_id',productId).eq('size',size);if(error)throw error}
async function mergeGuestIntoUser(){const guest=getGuest();if(!guest.length)return;const c=getDb()||((await loadSupabase())&&getDb());if(!c)return;const u=await currentUser();if(!u)return;await mergeGuestToUser(c,u,guest)}
window.sixpackCart={getCart,addToCart,removeFromCart,changeQty,mergeGuestIntoUser,loadSupabase};