const SUPABASE_URL='https://boaqzdyfsosswqvjgsjn.supabase.co';
const SUPABASE_KEY='sb_publishable_'+'JlneB01f5LDJ4VBO_n1E7Q_jXn5JBky';
const db=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const fallbackImage='/assets/d2060b27-276c-44c6-89d1-860f5908fb0b.png';
const qs=new URLSearchParams(location.search),view=qs.get('view')||'shop';
const requestedCategory=qs.get('category'),requestedBrand=qs.get('brand');
let active=requestedCategory||requestedBrand||'New In',products=[],inventory=new Map(),saved=new Set();
const root=document.getElementById('grid'),title=document.getElementById('title'),count=document.getElementById('count'),searchInput=document.getElementById('search');
const esc=s=>String(s??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));
const money=p=>`$${Number(p||0).toFixed(2)}`;
try{saved=new Set(JSON.parse(localStorage.getItem('6pw-saved')||'[]').map(String))}catch{}
const cartReady=new Promise(resolve=>{if(window.sixpackCart)return resolve();const s=document.createElement('script');s.src='/cart.js?v=20260907-engine';s.onload=resolve;s.onerror=resolve;document.head.appendChild(s)});
function rows(p){return inventory.get(String(p.id))||[]}
function qty(p,size){const r=rows(p).find(x=>String(x.size)===String(size));return r?Math.max(0,Number(r.stock||0)-Number(r.reserved||0)):0}
function total(p){const r=rows(p);return r.length?r.reduce((n,x)=>n+Math.max(0,Number(x.stock||0)-Number(x.reserved||0)),0):Number(p.stock||0)}
function sizes(p){const r=rows(p);if(r.length)return r.filter(x=>Number(x.stock||0)-Number(x.reserved||0)>0).map(x=>String(x.size));return Array.isArray(p.sizes)&&Number(p.stock||0)>0?p.sizes:[]}
function hay(p){return `${p.name||''} ${p.brand||''} ${p.category||''} ${p.style||''} ${p.color||''}`.toLowerCase()}
function matches(p){if(String(p.gender||'men').toLowerCase()!=='men')return false;if(view==='saved')return saved.has(String(p.id));if(view==='brands'&&requestedBrand)return String(p.brand||'').toLowerCase()===requestedBrand.toLowerCase();if(view==='newdrops'||view==='search'||view==='looks')return true;if(active==='New In')return true;if(active==='Clothing')return /t-shirts|hoodies|shirts|outerwear|pants|knitwear|swimwear|jeans|polos/i.test(p.category||'');if(active==='Shoes')return /shoe|sneaker|trainer|boot/i.test(p.category||'');if(active==='Accessories')return /accessor/i.test(p.category||'');if(active==='Sports'||active==='Sport')return /sport|running|training|performance/i.test(hay(p));if(active==='Sale')return Number(p.price||0)<=100;if(active==='Streetwear')return /streetwear/i.test(hay(p));if(active==='Luxury')return /luxury|premium/i.test(hay(p));return String(p.category||'').toLowerCase()===active.toLowerCase()||String(p.style||'').toLowerCase()===active.toLowerCase()||String(p.brand||'').toLowerCase()===active.toLowerCase()}
function score(p){const fresh=Math.max(0,100-(Date.now()-new Date(p.created_at||Date.now()).getTime())/86400000);return Number(p.bestseller_score||0)*4+Number(p.sold_count||0)*2+Math.min(total(p),30)*1.5+fresh+Number(p.rating||0)*10}
function badge(p){const a=total(p);if(!a)return'OUT OF STOCK';if(Number(p.compare_at_price||0)>Number(p.price||0))return'SALE';if(Number(p.sold_count||0)>8)return'SELLING FAST';if(Number(p.bestseller_score||0)>15)return'BESTSELLER';return view==='newdrops'?'NEW IN':p.category||'MEN'}
function card(p,i){const a=total(p),ss=sizes(p),out=!a;return `<article class="card ${out?'isOut':''}"><a class="productLink" href="/product.html?id=${encodeURIComponent(p.id)}"><div class="image"><button class="heart" type="button" data-save="${i}">${saved.has(String(p.id))?'♥':'♡'}</button><img src="${esc(p.image||fallbackImage)}" alt="${esc(p.name)}" loading="lazy"><span class="badge">${esc(badge(p))}</span>${out?'<div class="stockOverlay">OUT OF STOCK</div>':''}</div><div class="meta"><div class="brand">${esc(p.brand||'6PACKWEAR')}</div><div class="name">${esc(p.name||'Untitled product')}</div><div class="price">${money(p.price)}${Number(p.compare_at_price||0)>Number(p.price||0)?` <del>${money(p.compare_at_price)}</del>`:''}</div><div class="sub">${out?'Currently unavailable':`${ss.length} size${ss.length===1?'':'s'} available`}</div>${ss.length?`<div class="sizesMini">${ss.slice(0,8).map(s=>`<span>${esc(s)}</span>`).join('')}</div>`:''}</div></a><button class="quick ${out?'notify':''}" type="button" data-add="${i}" ${out?'':' '}>${out?'Notify me':'Select size · Add to bag'}</button></article>`}
function injectStyles(){if(document.getElementById('engineStyles'))return;const s=document.createElement('style');s.id='engineStyles';s.textContent='.stockOverlay{position:absolute;inset:0;display:flex;align-items:center;justify-content:center;background:rgba(0,0,0,.5);font-size:10px;font-weight:900;letter-spacing:.16em}.isOut .image img{filter:grayscale(1);opacity:.5}.meta del{color:#666;margin-left:6px}.sizesMini{display:flex;gap:4px;flex-wrap:wrap;margin-top:8px}.sizesMini span{border:1px solid #2d2d2d;color:#888;padding:3px 5px;font-size:7px}.sizeModal{position:fixed;inset:0;background:rgba(0,0,0,.76);display:none;align-items:center;justify-content:center;z-index:200}.sizeModal.show{display:flex}.sizeBox{width:min(460px,calc(100vw - 28px));background:#0d0d0d;border:1px solid #333;padding:28px}.sizeBox h3{margin:0 0 8px;font-size:24px;text-transform:uppercase}.sizeBox p{color:#888;font-size:11px;margin:0 0 22px}.sizeOptions{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.sizeOptions button{background:#090909;color:#fff;border:1px solid #3b3b3b;padding:14px;cursor:pointer}.sizeOptions button:hover{background:#f4f4f0;color:#050505}.sizeClose{margin-top:18px;width:100%;height:42px;background:none;border:1px solid #333;color:#aaa;cursor:pointer}@media(max-width:600px){.sizeOptions{grid-template-columns:repeat(3,1fr)}}';document.head.appendChild(s)}
function ensureModal(){if(document.getElementById('sizeModal'))return;const m=document.createElement('div');m.id='sizeModal';m.className='sizeModal';m.innerHTML='<div class="sizeBox"><h3 id="sizeTitle">Select size</h3><p id="sizeSub">Choose your size</p><div id="sizeOptions" class="sizeOptions"></div><button id="sizeClose" class="sizeClose">Cancel</button></div>';document.body.appendChild(m);m.onclick=e=>{if(e.target===m)m.classList.remove('show')};document.getElementById('sizeClose').onclick=()=>m.classList.remove('show')}
async function chooseSize(p){ensureModal();const m=document.getElementById('sizeModal'),opts=document.getElementById('sizeOptions'),available=sizes(p);document.getElementById('sizeTitle').textContent=p.name||'Select size';document.getElementById('sizeSub').textContent=`${p.brand||'6PACKWEAR'} · ${money(p.price)}`;opts.innerHTML=(Array.isArray(p.sizes)&&p.sizes.length?p.sizes:available).map(s=>{const n=qty(p,s);return `<button data-size="${esc(s)}" ${n<=0?'disabled style="opacity:.35;text-decoration:line-through"':''}>${esc(s)}<small style="display:block;color:#777;font-size:8px;margin-top:4px">${n>0?`${n} available`:'Out of stock'}</small></button>`}).join('');m.classList.add('show');opts.querySelectorAll('button:not([disabled])').forEach(b=>b.onclick=async()=>{m.classList.remove('show');await cartReady;try{await window.sixpackCart.addToCart(p,b.dataset.size,1);refreshBag();toast(`${p.name} · ${b.dataset.size} added to bag`)}catch(e){toast(e.message==='SIZE_REQUIRED'?'Select a size':'This size is no longer available')}})}
async function notify(p){const email=prompt('Email for restock notification');if(!email)return;const s=(Array.isArray(p.sizes)&&p.sizes[0])||'';await db.from('stock_alerts').insert({email,product_id:p.id,size:s});toast('Restock alert requested')}
function toast(t){const x=document.getElementById('toast');if(!x)return;x.textContent=t;x.classList.add('show');clearTimeout(window._toast);window._toast=setTimeout(()=>x.classList.remove('show'),1800)}
async function refreshBag(){await cartReady;try{const c=await window.sixpackCart.getCart();const n=c.reduce((a,x)=>a+Number(x.quantity||0),0);const b=document.getElementById('bagCount');if(b)b.textContent=n}catch{}}
function sortItems(a){const s=document.getElementById('sort')?.value||'recommended';if(s==='low')return a.sort((x,y)=>Number(x.price||0)-Number(y.price||0));if(s==='high')return a.sort((x,y)=>Number(y.price||0)-Number(x.price||0));if(s==='new')return a.sort((x,y)=>new Date(y.created_at)-new Date(x.created_at));if(s==='stock')return a.sort((x,y)=>total(y)-total(x));if(s==='rating')return a.sort((x,y)=>Number(y.rating||0)-Number(x.rating||0));return a.sort((x,y)=>score(y)-score(x))}
function render(){root.className='grid';let arr=sortItems(products.filter(matches));const q=(searchInput.value||'').trim().toLowerCase();if(q)arr=arr.filter(p=>hay(p).includes(q));title.textContent=view==='saved'?'Saved':view==='brands'?(requestedBrand||'Brands'):view==='newdrops'?'New Drops':view==='search'?'Search':active;count.textContent=`${arr.length} styles`;root.innerHTML=arr.length?arr.map(card).join(''):`<div style="grid-column:1/-1;padding:80px 0;color:#777">${view==='saved'?'No saved items yet.':'No products found.'}</div>`;root.querySelectorAll('[data-save]').forEach(b=>b.onclick=e=>{e.preventDefault();e.stopPropagation();const p=arr[+b.dataset.save];const k=String(p.id);saved.has(k)?saved.delete(k):saved.add(k);localStorage.setItem('6pw-saved',JSON.stringify([...saved]));render()});root.querySelectorAll('[data-add]').forEach(b=>b.onclick=e=>{e.preventDefault();e.stopPropagation();const p=arr[+b.dataset.add];total(p)?chooseSize(p):notify(p)})}
function setActive(v){active=v;history.replaceState({},'',`/catalog.html?view=shop&category=${encodeURIComponent(v)}`);render()}
document.querySelectorAll('[data-filter]').forEach(x=>x.onclick=e=>{e.preventDefault();setActive(x.dataset.filter);document.querySelectorAll('.mega').forEach(m=>m.classList.remove('open'))});
searchInput.oninput=render;searchInput.onkeydown=e=>{if(e.key==='Enter'){history.replaceState({},'',`/catalog.html?view=search&q=${encodeURIComponent(searchInput.value)}`);render()}};if(view==='search')searchInput.value=qs.get('q')||'';
document.getElementById('sort').onchange=render;document.getElementById('filterBtn').onclick=()=>document.getElementById('drawer').style.display='block';document.getElementById('close').onclick=()=>document.getElementById('drawer').style.display='none';document.getElementById('apply').onclick=()=>{document.getElementById('drawer').style.display='none';render()};
document.getElementById('accountBtn').onclick=()=>location.href='/';document.getElementById('savedBtn').onclick=()=>location.href='/catalog.html?view=saved';document.getElementById('bagBtn').onclick=()=>location.href='/cart.html';document.getElementById('bagCount').textContent='0';
document.querySelectorAll('.megaTrigger').forEach(t=>t.onclick=e=>{e.preventDefault();const m=t.closest('.mega');document.querySelectorAll('.mega').forEach(x=>{if(x!==m)x.classList.remove('open')});m.classList.toggle('open')});document.addEventListener('click',e=>{if(!e.target.closest('.mega'))document.querySelectorAll('.mega').forEach(m=>m.classList.remove('open'))});
(async()=>{injectStyles();ensureModal();const r=await db.from('products').select('id,name,brand,category,style,price,stock,sizes,color,image,created_at,gender,compare_at_price,rating,review_count,bestseller_score,view_count,sold_count').order('created_at',{ascending:false});if(r.error){count.textContent='Catalog unavailable';return}products=(r.data||[]).filter(p=>String(p.gender||'men').toLowerCase()==='men');const ids=products.map(p=>p.id);if(ids.length){const ir=await db.from('product_inventory').select('product_id,size,stock,reserved').in('product_id',ids);(ir.data||[]).forEach(x=>{const k=String(x.product_id);if(!inventory.has(k))inventory.set(k,[]);inventory.get(k).push(x)})}render();refreshBag()})();